const homeThemeTokens = {
  bgPrimary: 'bg-[var(--color-bg-primary)]',
  bgSecondary: 'bg-[var(--color-bg-secondary)]',
  bgTertiary: 'bg-[var(--color-bg-tertiary)]',
  accentPrimary: 'text-[var(--color-accent-primary)]',
  accentSubtleBg: 'bg-[var(--color-accent-subtle)]',
  textPrimary: 'text-[var(--color-text-primary)]',
  textSecondary: 'text-[var(--color-text-secondary)]',
  borderLight: 'border-[var(--color-border-light)]',
  borderDefault: 'border-[var(--color-border-default)]',
};

export const homeStyles = {
  pageRoot: `relative isolate w-full flex-1 flex flex-col items-center justify-center overflow-hidden ${homeThemeTokens.bgPrimary}`,
  backdropGrid: `pointer-events-none absolute inset-0 opacity-40 [mask-image:radial-gradient(ellipse_at_center,black_32%,transparent_78%)] bg-[linear-gradient(to_right,var(--color-border-light)_1px,transparent_1px),linear-gradient(to_bottom,var(--color-border-light)_1px,transparent_1px)] bg-[size:36px_36px]`,
  backdropOrbPrimary: 'pointer-events-none absolute -top-24 left-1/2 h-72 w-72 -translate-x-[58%] rounded-full bg-[var(--color-accent-primary)]/15 blur-3xl',
  backdropOrbSecondary: `pointer-events-none absolute -bottom-24 left-1/2 h-72 w-[34rem] -translate-x-1/2 rounded-full ${homeThemeTokens.bgTertiary}/80 blur-3xl`,
  backdropBottomBlend: `pointer-events-none absolute inset-x-0 bottom-0 h-48 bg-gradient-to-b from-transparent via-[var(--color-bg-primary)]/70 to-[var(--color-bg-primary)]`,
  contentContainer: 'relative z-10 max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-10 py-10 sm:py-14 lg:py-16',
  sectionSpacing: 'mb-12 sm:mb-16 lg:mb-20',
  heroHeader: 'relative text-center px-2 sm:px-4 lg:px-6 py-2 sm:py-4',
  heroBadge: `inline-flex items-center gap-2 px-3 py-1 rounded-full border ${homeThemeTokens.borderDefault} ${homeThemeTokens.accentSubtleBg} ${homeThemeTokens.accentPrimary} text-xs sm:text-sm font-medium mb-5 sm:mb-6`,
  heroBadgePing: `animate-ping absolute inline-flex h-full w-full rounded-full bg-[var(--color-accent-primary)] opacity-75`,
  heroBadgeDot: 'relative inline-flex rounded-full h-2 w-2 bg-[var(--color-accent-primary)]',
  heroTitle: `text-3xl sm:text-5xl lg:text-6xl font-semibold ${homeThemeTokens.textPrimary} mb-3 sm:mb-4 text-balance tracking-tight`,
  heroDescription: `text-base sm:text-lg ${homeThemeTokens.textSecondary} max-w-2xl mx-auto mb-6 sm:mb-8 text-pretty leading-relaxed`,
  heroCtaButton: 'group gap-2 w-full sm:w-auto shadow-[0_16px_34px_-20px_var(--color-accent-primary)]',
  heroCtaIcon: 'w-4 h-4 transition-transform duration-200 group-hover:translate-x-0.5',
  featureGrid: 'grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4 lg:gap-5',
  featureCard: `group h-full p-4 sm:p-5 lg:p-6 rounded-2xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgPrimary} hover:${homeThemeTokens.borderDefault} transition-all duration-300 hover:shadow-[0_8px_16px_-8px_rgba(15,23,42,0.6)]`,
  featureIconWrap: `inline-flex items-center justify-center w-10 h-10 sm:w-11 sm:h-11 lg:w-12 lg:h-12 rounded-lg ${homeThemeTokens.bgSecondary} ${homeThemeTokens.textPrimary} mb-3 sm:mb-4 group-hover:${homeThemeTokens.accentSubtleBg} group-hover:${homeThemeTokens.accentPrimary} transition-all duration-300 group-hover:scale-105`,
  featureTitle: `text-sm sm:text-base font-medium ${homeThemeTokens.textPrimary} mb-1.5 sm:mb-2`,
  featureDescription: `text-sm ${homeThemeTokens.textSecondary} leading-6`,
};
