const homeThemeTokens = {
  bgPrimary: 'bg-[var(--color-bg-primary)]',
  bgSecondary: 'bg-[var(--color-bg-secondary)]',
  bgTertiary: 'bg-[var(--color-bg-tertiary)]',
  accentPrimary: 'text-[var(--color-accent-primary)]',
  accentSubtleBg: 'bg-[var(--color-accent-subtle)]',
  textPrimary: 'text-[var(--color-text-primary)]',
  textSecondary: 'text-[var(--color-text-secondary)]',
  borderLight: 'border-[var(--color-border-light)]',
  borderDefault: 'border-[var(--color-border-default)]',
};

export const homeStyles = {
  pageRoot: `relative isolate w-full flex-1 overflow-hidden ${homeThemeTokens.bgPrimary}`,
  backdropGrid: `pointer-events-none absolute inset-0 opacity-20 dark:opacity-15 [mask-image:radial-gradient(ellipse_at_center,black_32%,transparent_78%)] bg-[linear-gradient(to_right,var(--color-border-light)_1px,transparent_1px),linear-gradient(to_bottom,var(--color-border-light)_1px,transparent_1px)] bg-[size:36px_36px]`,
  backdropOrbPrimary: 'pointer-events-none absolute -top-24 left-1/2 h-72 w-72 -translate-x-[58%] rounded-full bg-[var(--color-accent-primary)]/15 blur-3xl',
  backdropOrbSecondary: `pointer-events-none absolute -bottom-24 left-1/2 h-72 w-[34rem] -translate-x-1/2 rounded-full ${homeThemeTokens.bgTertiary}/40 blur-3xl`,
  backdropBottomBlend: `pointer-events-none absolute inset-x-0 bottom-0 h-48 bg-gradient-to-b from-transparent via-[var(--color-bg-primary)]/70 to-[var(--color-bg-primary)]`,
  contentContainer: 'relative z-10 max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-10 py-10 sm:py-14 lg:py-16',
  sectionSpacing: 'mb-12 sm:mb-16 lg:mb-20',
  sectionHeaderWrap: 'flex flex-col items-start gap-2 mb-6 sm:mb-8',
  sectionKicker: `text-xs font-semibold tracking-wide ${homeThemeTokens.accentPrimary}`,
  sectionTitle: `text-xl sm:text-2xl font-semibold ${homeThemeTokens.textPrimary} tracking-tight`,
  sectionDescription: `text-sm sm:text-base ${homeThemeTokens.textSecondary} max-w-2xl leading-relaxed`,
  heroHeader: 'relative text-center px-2 sm:px-4 lg:px-6 py-2 sm:py-4',
  heroBadge: `inline-flex items-center gap-2 px-3 py-1 rounded-full border ${homeThemeTokens.borderDefault} ${homeThemeTokens.accentSubtleBg} ${homeThemeTokens.accentPrimary} text-xs sm:text-sm font-medium mb-5 sm:mb-6`,
  heroBadgePing: `absolute inline-flex h-full w-full rounded-full bg-[var(--color-accent-primary)] opacity-20`,
  heroBadgeDot: 'relative inline-flex rounded-full h-2 w-2 bg-[var(--color-accent-primary)]',
  heroTitle: `text-3xl sm:text-5xl lg:text-6xl font-semibold ${homeThemeTokens.textPrimary} mb-3 sm:mb-4 text-balance tracking-tight`,
  heroDescription: `text-base sm:text-lg ${homeThemeTokens.textSecondary} max-w-2xl mx-auto mb-6 sm:mb-8 text-pretty leading-relaxed`,
  heroCtaButton: 'group gap-2 w-full sm:w-auto',
  heroCtaIcon: 'w-4 h-4 transition-transform duration-200 group-hover:translate-x-0.5',
  logoCloudWrap: `rounded-2xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} px-4 sm:px-6 py-5 sm:py-6`,
  logoCloudGrid: 'flex flex-wrap items-center justify-center gap-2 sm:gap-2.5',
  logoCloudTitle: `text-xs font-semibold ${homeThemeTokens.textSecondary} text-center mb-3`,
  showcaseGrid: 'grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-6 items-stretch',
  showcasePanel: `rounded-2xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} overflow-hidden`,
  showcasePanelHeader: `flex items-center justify-between px-4 py-3 border-b ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary}`,
  showcasePanelDots: 'flex items-center gap-1.5',
  showcaseDotRed: 'w-2 h-2 rounded-full bg-[#ff5f56]',
  showcaseDotYellow: 'w-2 h-2 rounded-full bg-[#ffbd2e]',
  showcaseDotGreen: 'w-2 h-2 rounded-full bg-[#27c93f]',
  showcaseTabBar: 'flex items-center gap-1.5',
  showcaseCodeBody: `px-4 py-4 ${homeThemeTokens.bgSecondary}`,
  terminalBlock:
    'rounded-xl border border-[color-mix(in_srgb,#ffffff_14%,transparent)] bg-[radial-gradient(circle_at_18%_20%,rgba(27,89,184,0.22),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.06),transparent_35%),#0b1315] overflow-hidden',
  terminalInner:
    'p-4 font-mono text-[12px] leading-5 text-[#d0d7de] h-[220px] overflow-auto scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent',
  terminalLine: 'flex items-start gap-2',
  terminalPrefix: 'shrink-0 w-12 tabular-nums',
  terminalPrefixPrompt: 'text-[color-mix(in_srgb,var(--color-accent-primary)_70%,#ffffff)]',
  terminalPrefixMuted: 'text-[#8a9aa6]',
  terminalText: 'min-w-0 whitespace-pre',
  terminalOutputText: 'text-[#8a9aa6]',
  terminalOkText: 'text-[color-mix(in_srgb,var(--color-success)_82%,#ffffff)]',
  terminalKeyword: 'text-[color-mix(in_srgb,var(--color-accent-primary)_75%,#ffffff)]',
  terminalSeparator: 'text-[#3a4a56]',
  caret: 'inline-block w-2 h-4 align-[-3px] bg-[#e6edf3] opacity-90 animate-pulse',
  miniDashboard: 'p-5 sm:p-6 flex flex-col gap-4',
  miniStatGrid: 'grid grid-cols-2 gap-3',
  miniStatCard: `rounded-xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} p-3`,
  miniStatLabel: `text-[11px] font-semibold ${homeThemeTokens.textSecondary}`,
  miniStatValue: `mt-1 text-base font-semibold ${homeThemeTokens.textPrimary} tabular-nums`,
  miniStatNote: `mt-1 text-xs ${homeThemeTokens.textSecondary} leading-relaxed`,
  statsGrid: 'grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4',
  statCard: `rounded-2xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} p-5 sm:p-6`,
  statLabel: `text-xs font-semibold ${homeThemeTokens.textSecondary}`,
  statValue: `mt-2 text-2xl font-semibold ${homeThemeTokens.textPrimary} tracking-tight`,
  statDescription: `mt-2 text-sm ${homeThemeTokens.textSecondary} leading-relaxed`,
  testimonialGrid: 'grid grid-cols-1 lg:grid-cols-3 gap-3 sm:gap-4',
  testimonialCard: `rounded-2xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} p-5 sm:p-6`,
  testimonialQuote: `text-sm ${homeThemeTokens.textSecondary} leading-relaxed`,
  testimonialMeta: 'mt-4 flex items-center justify-between gap-3',
  testimonialAuthor: `text-sm font-semibold ${homeThemeTokens.textPrimary}`,
  testimonialRole: 'text-xs text-[var(--color-text-tertiary)]',
  finalCtaWrap: `relative overflow-hidden rounded-3xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary}`,
  finalCtaInner: 'relative z-10 px-6 sm:px-10 py-10 sm:py-12 flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6',
  finalCtaTitle: `text-2xl sm:text-3xl font-semibold ${homeThemeTokens.textPrimary} tracking-tight`,
  finalCtaDesc: `mt-2 text-sm sm:text-base ${homeThemeTokens.textSecondary} max-w-xl leading-relaxed`,
  finalCtaBackdrop: 'pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(27,89,184,0.22),transparent_55%),radial-gradient(circle_at_70%_35%,rgba(75,134,242,0.18),transparent_55%),radial-gradient(circle_at_40%_80%,rgba(0,45,178,0.18),transparent_55%)]',
  featureGrid: 'grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4 lg:gap-5',
  featureCard: `group h-full p-4 sm:p-5 lg:p-6 rounded-xl border ${homeThemeTokens.borderLight} ${homeThemeTokens.bgSecondary} hover:${homeThemeTokens.borderDefault} transition-[border-color,box-shadow] duration-300 hover:shadow-[var(--shadow-sm)]`,
  featureIconWrap: `inline-flex items-center justify-center w-10 h-10 sm:w-11 sm:h-11 lg:w-12 lg:h-12 rounded-lg ${homeThemeTokens.bgSecondary} ${homeThemeTokens.textPrimary} mb-3 sm:mb-4 group-hover:${homeThemeTokens.accentSubtleBg} group-hover:${homeThemeTokens.accentPrimary} transition-colors duration-300`,
  featureTitle: `text-sm sm:text-base font-medium ${homeThemeTokens.textPrimary} mb-1.5 sm:mb-2`,
  featureDescription: `text-sm ${homeThemeTokens.textSecondary} leading-6`,
};
