{
 "title": "1.KaiwuDB Console: Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "SQL Queries",
   "type": "timeseries",
   "description": "A ten-second moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 99th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas per Node",
   "type": "timeseries",
   "description": "The number of range replicas stored on this node. Ranges are subsets of your data, which are replicated to ensure survivability.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "description": "Capacity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(capacity{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(sum(capacity_tsdb_used{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Time series used"
    },
    {
     "expr": "sum(sum(capacity_relational_used{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Relational used"
    },
    {
     "expr": "sum(sum(capacity{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) - sum(sum(capacity_available{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Total used"
    },
    {
     "expr": " sum(sum(capacity_available{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}