{
 "title": "2.Kaiwudb Console: Hardware",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "description": "CPU Percent",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "sys_cpu_combined_percent_normalized{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory Usage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_rss{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "description": "Disk Read Bytes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_read_bytes{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "description": "Disk Write Bytes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_write_bytes{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Ops",
   "type": "timeseries",
   "description": "Disk Read Ops",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_read_count{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Ops",
   "type": "timeseries",
   "description": "Disk Write Ops",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sys_host_disk_write_count{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOPS In Progress",
   "type": "timeseries",
   "description": "Disk IOPS In Progress. Generally, the smaller the value the better, indicating that the number of IO bottlenecks is less.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sys_host_disk_iopsinprogress{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity",
   "type": "timeseries",
   "description": "Available Disk Capacity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "capacity_available{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes Received",
   "type": "timeseries",
   "description": "Network Bytes Received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_net_recv_bytes{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes Sent",
   "type": "timeseries",
   "description": "Network Bytes Sent",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sys_host_net_send_bytes{job=\"kaiwudb\", cluster=~\"$cluster\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}