{
 "title": "3.KaiwuDB Console: Runtime",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Node Count",
   "type": "timeseries",
   "description": "The number of live nodes in the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(liveness_livenodes{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Live Nodes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory in use across all nodes:\nRSS  \nTotal memory in use by kaiwudb\n\nGo Allocated  \nMemory allocated by the Go layer\n\nGo Total  \nTotal memory managed by the Go layer\n\nC Allocated  \nMemory allocated by the C layer\n\nC Total  \nTotal memory managed by the C layer",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Total memory (RSS)"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_go_allocbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "Kmalloc memory request",
   "type": "timeseries",
   "description": "Kmalloc memory request",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_kmalloc_totalbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Total memory requested by Kamlloc"
    }
   ]
  },
  {
   "title": "Memory Map virtual size",
   "type": "timeseries",
   "description": "Memory Map virtual size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_memory_map_virtualbytes{job=\"kaiwudb\",instance=~\"$node\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Map physical size",
   "type": "timeseries",
   "description": "Memory Map physical size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sys_memory_map_physicalbytes{job=\"kaiwudb\",instance=~\"$node\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Map range count",
   "type": "timeseries",
   "description": "Memory Map range count",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sys_memory_map_totalcount{job=\"kaiwudb\",instance=~\"$node\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "description": "The number of Goroutines across all nodes. This count should rise and fall based on load.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sys_goroutines{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Goroutine Count"
    }
   ]
  },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "description": "The number of times that Go’s garbage collector was invoked per second across all nodes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Runs"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "description": "The amount of processor time used by Go’s garbage collector per second across all nodes. During garbage collection, application code execution is paused.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_gc_pause_ns{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Pause Time"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "description": "The amount of CPU time used by CockroachDB (User) and system-level operations (Sys).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "User CPU Time"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Sys CPU Time"
    }
   ]
  },
  {
   "title": "Clock Offset",
   "type": "timeseries",
   "description": "Mean clock offset of each node against the rest of the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "clock_offset_meannanos{job=\"kaiwudb\",instance=~\"$node\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}