{
 "title": "4.KaiwuDB Console: SQL",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Total SQL Connections",
   "type": "timeseries",
   "description": "The number of instantaneous SQL connections, including successfully established connections and connections that failed to establish, such as incorrect passwords or exceeding the maximum number of connections.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sql_conns{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful SQL connections",
   "type": "timeseries",
   "description": "The number of active and successful SQL connections established.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sql_suc_conns{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Byte Traffic",
   "type": "timeseries",
   "description": "The total amount of SQL client network traffic in bytes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(rate(sql_bytesout{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "timeseries",
   "description": "A ten-second moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(rate(sql_ddl_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "DDL"
    },
    {
     "expr": "sum(rate(sql_misc_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "SQL Query Errors",
   "type": "timeseries",
   "description": "The number of statements which returned a planning or runtime error.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Active Distributed SQL Queries",
   "type": "timeseries",
   "description": "The total number of distributed SQL queries currently running.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sql_distsql_queries_active{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Active Queries"
    }
   ]
  },
  {
   "title": "Active Flows for Distributed SQL Queries",
   "type": "timeseries",
   "description": "The number of flows on each node contributing to currently running distributed SQL queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sql_distsql_flows_active{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 99th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 90th percentile",
   "type": "timeseries",
   "description": "Over the last minute, this node executed 90% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of latency between query requests and responses over 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(exec_latency_bucket{job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency between query requests and responses over 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(exec_latency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "The total number of transactions initiated, committed, rolled back, or aborted per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate( sql_txn_rollback_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Aborts"
    }
   ]
  },
  {
   "title": "Transaction Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of total transaction time over 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(sql_txn_latency_bucket{job=\"kaiwudb\",cluster=\"$cluster\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of total transaction time over 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(sql_txn_latency_bucket{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schema Changes",
   "type": "timeseries",
   "description": "The total number of DDL statements per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$rate_interval]))  ",
     "legendFormat": "DDL Statements"
    }
   ]
  }
 ]
}