{
 "title": "5.KaiwuDB Console: Storage",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "timeseries",
   "description": "Capacity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(capacity{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Capacity"
    },
    {
     "expr": " sum(sum(capacity_available{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(sum(capacity_used{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Total used"
    },
    {
     "expr": "sum(sum(capacity_tsdb_used{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Time series used"
    },
    {
     "expr": "sum(sum(capacity_relational_used{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Relation used"
    }
   ]
  },
  {
   "title": "Live Bytes",
   "type": "timeseries",
   "description": "Amount of data that can be read by applications and KaiwuDB.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum(livebytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Log Commit Latency: 99th Percentile",
   "type": "timeseries",
   "description": "The 99th %ile latency for commits to the Raft Log. This measures essentially an fdatasync to the storage engine's write-ahead log.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_logcommit_latency_bucket{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Commit Latency: 50th Percentile",
   "type": "timeseries",
   "description": "The 50th %ile latency for commits to the Raft Log. This measures essentially an fdatasync to the storage engine's write-ahead log.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_logcommit_latency_bucket{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 99th Percentile",
   "type": "timeseries",
   "description": "The 99th %ile latency for commits of Raft commands. This measures applying a batch to the storage engine (including writes to the write-ahead log), but no fsync.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(raft_process_commandcommit_latency_bucket{job=\"kaiwudb\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Commit Latency: 50th Percentile",
   "type": "timeseries",
   "description": "The 50th %ile latency for commits of Raft commands. This measures applying a batch to the storage engine (including writes to the write-ahead log), but no fsync.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,rate(raft_process_commandcommit_latency_bucket{job=\"kaiwudb\", instance=~\"$node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification",
   "type": "timeseries",
   "description": "The average number of real read operations executed per logical read operation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "RocksDB SSTables",
   "type": "timeseries",
   "description": "The number of SSTables in use.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "description": "The number of open file descriptors, compared with the file descriptor limit.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Compactions/Flushes",
   "type": "timeseries",
   "description": "The number of compactions and memtable flushes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rocksdb_compactions{job=\"kaiwudb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Compactions"
    },
    {
     "expr": "sum(rate(rocksdb_flushes{job=\"kaiwudb\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Time Series Monitoring Data Sampling Writes",
   "type": "timeseries",
   "description": "The number of successfully written time series monitoring data samples, and number of errors attempting to write time series monitoring data, per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(timeseries_write_samples{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Samples Written"
    },
    {
     "expr": "sum(rate(timeseries_write_errors{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Time Series  Monitoring Data Written Bytes",
   "type": "timeseries",
   "description": "The number of bytes written by the time series system per second.Note that this does not reflect the rate at which disk space is consumed by time series; the data is highly compressed on disk. This rate is instead intended to indicate the amount of network traffic and disk activity generated by time series writes. See the \"databases\" tab to find the current disk usage for time series data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(timeseries_write_bytes{job=\"kaiwudb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bytes Written"
    }
   ]
  }
 ]
}