{
 "title": "6.KaiwuDB Console: Replication",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges",
   "type": "timeseries",
   "description": "Current Range Number",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(ranges{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})) by (instance)",
     "legendFormat": "Ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders"
    },
    {
     "expr": "sum(sum(replicas_leaseholders{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Lease Holders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Leaders w/o Lease"
    },
    {
     "expr": "sum(sum(ranges_unavailable{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Under-replicated"
    },
    {
     "expr": "sum(sum(ranges_overreplicated{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Over-replicated"
    }
   ]
  },
  {
   "title": "Replicas per Store",
   "type": "timeseries",
   "description": "The number of replicas on each store.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leaseholders per Store",
   "type": "timeseries",
   "description": "The number of leaseholder replicas on each store. A leaseholder replica is the one that receives and coordinates all read and write requests for its range.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Queries per Store",
   "type": "timeseries",
   "description": "Exponentially weighted moving average of the number of KV batch requests processed by leaseholder replicas on each store per second. Tracks roughly the last 30 minutes of requests. Used for load-based rebalancing decisions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rebalancing_queriespersecond{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logical Bytes per Store",
   "type": "timeseries",
   "description": "Logical Bytes per Store",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "totalbytes{job=\"kaiwudb\",cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica Quiescence",
   "type": "timeseries",
   "description": "Replica Quiescence",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))  ",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Quiescent"
    }
   ]
  },
  {
   "title": "Range Operations",
   "type": "timeseries",
   "description": "The number of Range operations, including splitting, merging, adding, removing, etc.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Splits"
    },
    {
     "expr": "sum(sum(rate(range_merges{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Merges"
    },
    {
     "expr": "sum(sum(rate(range_adds{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Add"
    },
    {
     "expr": "sum(sum(rate(range_removes{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Remove"
    },
    {
     "expr": "sum(sum(rate(leases_transfers_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_lease_transfers{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Lease Transfers"
    },
    {
     "expr": "sum(sum(rate(rebalancing_range_rebalances{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval])) by (instance))",
     "legendFormat": "Load-based Range Rebalances"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "timeseries",
   "description": "Snapshots",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Raft-initiated)"
    },
    {
     "expr": "sum(rate(range_snapshots_learner_applied{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied (Learner)"
    },
    {
     "expr": "sum(rate(replicas_reserved{cluster=~\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Reserved"
    },
    {
     "expr": "sum(rate(range_snapshots_preemtive_applied{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Applied(Preemptive)"
    }
   ]
  }
 ]
}