{
 "title": "7.KaiwuDB Console: Distribution",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Batches",
   "type": "timeseries",
   "description": "Batches",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_batches{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Batches"
    },
    {
     "expr": "sum(rate(distsender_batches_partial{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Partial Batches"
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "timeseries",
   "description": "RPCs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "RPCs Sent"
    },
    {
     "expr": "sum(rate(distsender_rpc_sent_local{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Local Fast-path"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "description": "RPC Errors",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent_sendnexttimeout{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "RPC Timeouts"
    },
    {
     "expr": "sum(rate(distsender_rpc_sent_nextreplicaerror{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Replica Errors"
    },
    {
     "expr": "sum(rate(distsender_errors_notleaseholder{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Not Leaseholder Errors"
    }
   ]
  },
  {
   "title": "KV Transactions",
   "type": "timeseries",
   "description": "KV transaction numbers, including committed, Fast-path committed, and aborted.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_commits{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(txn_commits1PC{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Fast-path Committed"
    },
    {
     "expr": "sum(rate(txn_aborts{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Aborted"
    }
   ]
  },
  {
   "title": "KV Transaction Restarts",
   "type": "timeseries",
   "description": "KV Transaction Restarts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(txn_restarts_writetooold{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Write Too Old"
    },
    {
     "expr": "sum(rate(txn_restarts_writetoooldmulti{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Write Too Old (multiple)"
    },
    {
     "expr": "sum(rate(txn_restarts_serializable{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Forwarded Timestamp (iso=serializable)"
    },
    {
     "expr": "sum(rate(txn_restarts_asyncwritefailure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Async Consensus Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_readwithinuncertainty{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Read Within Uncertainty Interval"
    },
    {
     "expr": "sum(rate(txn_restarts_txnaborted{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(txn_restarts_txnpush{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Push Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_unknown{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "KV Transaction Durations: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of transaction durations over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_99{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Transaction Durations: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of transaction durations over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "txn_durations:rate1m:quantile_90{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 99th percentile",
   "type": "timeseries",
   "description": "The 99th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(liveness_heartbeatlatency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 90th percentile",
   "type": "timeseries",
   "description": "The 90th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(liveness_heartbeatlatency_bucket{job=\"kaiwudb\",instance=~\"$node\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}