{
 "title": "8.KaiwuDB Console: Queue",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Queue Processing Failures",
   "type": "timeseries",
   "description": "Queue Processing Failures",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_process_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    },
    {
     "expr": "sum(rate(compactor_compactions_failure{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Compaction"
    }
   ]
  },
  {
   "title": "Queue Processing Times",
   "type": "timeseries",
   "description": "Queue Processing Times",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_processingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    },
    {
     "expr": "sum(rate(compactor_compactingnanos{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Compaction"
    }
   ]
  },
  {
   "title": "Replica GC Queue",
   "type": "timeseries",
   "description": "Replica GC Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_replicagc_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_replicagc_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicagc_removereplica{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    }
   ]
  },
  {
   "title": "Replication Queue",
   "type": "timeseries",
   "description": "Replication Queue Number",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_replicate_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicate_addreplica{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Added / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removereplica{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removedeadreplica{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Dead Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_rebalancereplica{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas Rebalanced / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_transferlease{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Leases Transferred / sec"
    },
    {
     "expr": "max(rate(queue_replicate_purgatory{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Replicas in Purgatory"
    }
   ]
  },
  {
   "title": "Split Queue",
   "type": "timeseries",
   "description": "Split Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_split_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_split_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Merge Queue",
   "type": "timeseries",
   "description": "Merge Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_merge_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_merge_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "GC Queue",
   "type": "timeseries",
   "description": "GC Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_gc_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Log Queue",
   "type": "timeseries",
   "description": "Raft Log Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_raftlog_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_raftlog_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Snapshot Queue",
   "type": "timeseries",
   "description": "Raft Snapshot Queue ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_raftsnapshot_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_raftsnapshot_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Consistency Checker Queue",
   "type": "timeseries",
   "description": "Consistency Checker Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_consistency_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_consistency_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Metrics Monitoring Data Maintenance Queue",
   "type": "timeseries",
   "description": "Metrics Monitoring Data Maintenance Queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(queue_tsmaintenance_process_success{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "max(queue_tsmaintenance_pending{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Compaction Queue",
   "type": "timeseries",
   "description": "The completed (or estimated) bytes of storage that were (or could be) reclaimed by forcing compactions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(compactor_suggestionbytes_compacted{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Bytes compacted / sec"
    },
    {
     "expr": "max(compactor_suggestionbytes_queued{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"})",
     "legendFormat": "Queued bytes"
    }
   ]
  }
 ]
}