{
 "title": "9.KaiwuDB Console: Slow Query",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "sys_uptime{job=\"kaiwudb\"}"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"kaiwudb\",cluster=\"$cluster\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Slow Raft Proposals",
   "type": "timeseries",
   "description": "Proposals in Raft, including elections and log replication, become slow",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(requests_slow_raft{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Slow Raft Proposals"
    }
   ]
  },
  {
   "title": "Slow DistSender RPCs",
   "type": "timeseries",
   "description": "Slow remote procedure call (RPC) between different nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(requests_slow_distsender{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Slow DistSender RPCs"
    }
   ]
  },
  {
   "title": "Slow Lease Acquisitions",
   "type": "timeseries",
   "description": "In distributed systems, Lease is usually used to coordinate and synchronize operations, and lease acquisition is slow",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(requests_slow_lease{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Slow Lease Acquisitions"
    }
   ]
  },
  {
   "title": "Slow Latch Acquisitions",
   "type": "timeseries",
   "description": "Latch is a low-level mechanism for synchronization, used to protect shared resources.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(requests_slow_latch{cluster=\"$cluster\",job=\"kaiwudb\",instance=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Slow Latch Acquisitions"
    }
   ]
  }
 ]
}